# Module 1 — Data Cleaning and Transformation
## Healthcare Dataset

**Student:** Meisam Abolhassani  
**Course:** Data Preprocessing and Data Pipeline  
**Date:** September 2026

In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

print("Libraries loaded successfully")

Libraries loaded successfully

In [12]:
df = pd.read_excel("healthcare_raw.xlsx")
df

   Patient_ID       Admission_Date        Name   Age  Gender     Diagnosis Blood_Pressure  Heart_Rate  Medication Doctor_Assigned  Contact_Number             Email
0           1           12-03-2023  John Smith  45.0    Male      Diabetes         130/85        72.0   Metformin       Dr. Adams    9.876543e+09    john@email.com
1           2           13/03/2023    Jane Doe  32.0  Female  Hypertension            NaN        80.0  Lisinopril       Dr. Brown    8.765432e+09        jane@email
2           3  2014-03-23 00:00:00  Mike Jones  29.0    Male           Flu         120/80         NaN   Ibuprofen       Dr. Adams    7.654321e+09  mike.j@email.com
3           4           15/03/2023   Sarah Lee   NaN  Female      Diabetes         135/90        76.0   Metformin       Dr. White    6.543211e+09   sarah@email.com
4           5           16-03-2023  Chris Paul  50.0    Male  Hypertension         140/95        85.0  Lisinopril       Dr. Brown             NaN   chris@email.com
5           6  2017-03-23 00:00:00  Emily Rose  41.0  Female        Asthma         125/85        78.0   Albuterol       Dr. Adams    5.432110e+09  emily.rose@email
6           7           18-03-2023  Kevin Hart  38.0    Male           Flu         118/75        70.0   Ibuprofen       Dr. White    4.321099e+09   kevin@email.com
7           8           19/03/2023  Olivia Kim  47.0  Female  Hypertension        145/100        88.0  Lisinopril       Dr. Brown    3.210988e+09  olivia@email.com
8           9  2020-03-23 00:00:00  Daniel Lee  52.0    Male      Diabetes         130/90        82.0   Metformin       Dr. White    2.109877e+09  daniel@email.com

In [13]:
df_raw = df.copy()

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 9
Columns: 12

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Patient_ID       9 non-null      int64
 1   Admission_Date   9 non-null      object
 2   Name             9 non-null      object
 3   Age              8 non-null      float64
 4   Gender           9 non-null      object
 5   Diagnosis        9 non-null      object
 6   Blood_Pressure   8 non-null      object
 7   Heart_Rate       8 non-null      float64
 8   Medication       9 non-null      object
 9   Doctor_Assigned  9 non-null      object
 10  Contact_Number   8 non-null      float64
 11  Email            9 non-null      object
dtypes: float64(3), int64(1), object(8)
memory usage: 996.0+ bytes

In [15]:
df.isnull().sum()

Patient_ID         0
Admission_Date     0
Name               0
Age                1
Gender             0
Diagnosis          0
Blood_Pressure     1
Heart_Rate         1
Medication         0
Doctor_Assigned    0
Contact_Number     1
Email              0
dtype: int64

## Task 1 — Identify Data Issues
No changes are made in this section. Each issue is detected and documented using code.

In [16]:
missing_report = pd.DataFrame({
    'Missing_Count': df.isnull().sum(),
    'Missing_Percent': (df.isnull().sum() / len(df) * 100).round(2)
})

missing_report[missing_report['Missing_Count'] > 0]

                Missing_Count  Missing_Percent
Age                         1            11.11
Blood_Pressure              1            11.11
Heart_Rate                  1            11.11
Contact_Number              1            11.11

In [17]:
df[df.isnull().any(axis=1)]

   Patient_ID       Admission_Date        Name   Age  Gender     Diagnosis Blood_Pressure  Heart_Rate  Medication Doctor_Assigned  Contact_Number             Email
1           2           13/03/2023    Jane Doe  32.0  Female  Hypertension            NaN        80.0  Lisinopril       Dr. Brown    8.765432e+09        jane@email
2           3  2014-03-23 00:00:00  Mike Jones  29.0    Male           Flu         120/80         NaN   Ibuprofen       Dr. Adams    7.654321e+09  mike.j@email.com
3           4           15/03/2023   Sarah Lee   NaN  Female      Diabetes         135/90        76.0   Metformin       Dr. White    6.543211e+09   sarah@email.com
4           5           16-03-2023  Chris Paul  50.0    Male  Hypertension         140/95        85.0  Lisinopril       Dr. Brown             NaN   chris@email.com

In [18]:
date_check = pd.DataFrame({
    'Patient_ID': df['Patient_ID'],
    'Admission_Date': df['Admission_Date'],
    'Python_Type': [type(v).__name__ for v in df['Admission_Date']]
})

date_check

   Patient_ID       Admission_Date Python_Type
0           1           12-03-2023         str
1           2           13/03/2023         str
2           3  2014-03-23 00:00:00    datetime
3           4           15/03/2023         str
4           5           16-03-2023         str
5           6  2017-03-23 00:00:00    datetime
6           7           18-03-2023         str
7           8           19/03/2023         str
8           9  2020-03-23 00:00:00    datetime

In [19]:
import re

email_pattern = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
is_valid = df['Email'].astype(str).str.match(email_pattern)

pd.DataFrame({
    'Patient_ID': df['Patient_ID'],
    'Email': df['Email'],
    'Is_Valid': is_valid
})

   Patient_ID             Email  Is_Valid
0           1    john@email.com      True
1           2        jane@email     False
2           3  mike.j@email.com      True
3           4   sarah@email.com      True
4           5   chris@email.com      True
5           6  emily.rose@email     False
6           7   kevin@email.com      True
7           8  olivia@email.com      True
8           9  daniel@email.com      True

In [20]:
print("Data type:", df['Blood_Pressure'].dtype)
print()
print(df[['Patient_ID', 'Blood_Pressure']].to_string(index=False))

Data type: object

 Patient_ID Blood_Pressure
          1         130/85
          2            NaN
          3         120/80
          4         135/90
          5         140/95
          6         125/85
          7         118/75
          8        145/100
          9         130/90

In [21]:
print("Gender values:", df['Gender'].unique())
print("Diagnosis values:", df['Diagnosis'].unique())
print("Contact_Number dtype:", df['Contact_Number'].dtype)

Gender values: ['Male' 'Female']
Diagnosis values: ['Diabetes' 'Hypertension' 'Flu' 'Asthma']
Contact_Number dtype: float64

## Task 2 — Data Cleaning

### 2.1 Standardizing the Admission Date

In [22]:
naive = pd.to_datetime(df['Admission_Date'], dayfirst=True, errors='coerce')

pd.DataFrame({
    'Patient_ID': df['Patient_ID'],
    'Original': df['Admission_Date'].astype(str),
    'Naive_Result': naive
})

   Patient_ID             Original Naive_Result
0           1           12-03-2023   2023-03-12
1           2           13/03/2023          NaT
2           3  2014-03-23 00:00:00   2014-03-23
3           4           15/03/2023          NaT
4           5           16-03-2023   2023-03-16
5           6  2017-03-23 00:00:00   2017-03-23
6           7           18-03-2023   2023-03-18
7           8           19/03/2023          NaT
8           9  2020-03-23 00:00:00   2020-03-23

In [23]:
from datetime import datetime

def fix_admission_date(value):
    """
    Two cases exist in this column.

    Case 1 - the value is already a datetime.
    Excel read the original text DD-MM-YY as YY-MM-DD,
    so the day and the year must be swapped back.

    Case 2 - the value is still text.
    Parsed with dayfirst=True to respect the DD-MM-YYYY order.
    """
    if isinstance(value, datetime):
        day   = value.year - 2000
        month = value.month
        year  = 2000 + value.day
        return pd.Timestamp(year=year, month=month, day=day)

    return pd.to_datetime(str(value).strip(), dayfirst=True, format='mixed')

In [24]:
df['Admission_Date'] = df['Admission_Date'].apply(fix_admission_date)

pd.DataFrame({
    'Patient_ID': df['Patient_ID'],
    'Original': df_raw['Admission_Date'].astype(str),
    'Cleaned': df['Admission_Date'].dt.strftime('%Y-%m-%d')
})

   Patient_ID             Original     Cleaned
0           1           12-03-2023  2023-03-12
1           2           13/03/2023  2023-03-13
2           3  2014-03-23 00:00:00  2023-03-14
3           4           15/03/2023  2023-03-15
4           5           16-03-2023  2023-03-16
5           6  2017-03-23 00:00:00  2023-03-17
6           7           18-03-2023  2023-03-18
7           8           19/03/2023  2023-03-19
8           9  2020-03-23 00:00:00  2023-03-20

In [25]:
print("Data type:", df['Admission_Date'].dtype)
print("Date range:", df['Admission_Date'].min().date(), "to", df['Admission_Date'].max().date())
print("All in March 2023:", ((df['Admission_Date'].dt.year == 2023) &
                             (df['Admission_Date'].dt.month == 3)).all())
print("Duplicate dates:", df['Admission_Date'].duplicated().sum())
print("Gaps between consecutive admissions (days):",
      sorted(df['Admission_Date'].diff().dropna().dt.days.unique()))

Data type: datetime64[ns]
Date range: 2023-03-12 to 2023-03-20
All in March 2023: True
Duplicate dates: 0
Gaps between consecutive admissions (days): [np.int64(1)]

### 2.2 Filling Missing Age With the Median

In [26]:
age_before = df['Age']

print("Missing values:", age_before.isnull().sum())
print("Mean  :", round(age_before.mean(), 2))
print("Median:", age_before.median())
print("Std   :", round(age_before.std(), 2))
print()
print("Values:", sorted(age_before.dropna().tolist()))

Missing values: 1
Mean  : 41.75
Median: 43.0
Std   : 8.31

Values: [29.0, 32.0, 38.0, 41.0, 45.0, 47.0, 50.0, 52.0]

In [27]:
median_age = df['Age'].median()

df['Age'] = df['Age'].fillna(median_age)
df['Age'] = df['Age'].round().astype(int)

print("Median used for imputation:", median_age)

Median used for imputation: 43.0

In [28]:
pd.DataFrame({
    'Patient_ID': df['Patient_ID'],
    'Name': df['Name'],
    'Age_Before': df_raw['Age'],
    'Age_After': df['Age']
})

   Patient_ID        Name  Age_Before  Age_After
0           1  John Smith        45.0         45
1           2    Jane Doe        32.0         32
2           3  Mike Jones        29.0         29
3           4   Sarah Lee         NaN         43
4           5  Chris Paul        50.0         50
5           6  Emily Rose        41.0         41
6           7  Kevin Hart        38.0         38
7           8  Olivia Kim        47.0         47
8           9  Daniel Lee        52.0         52

### 2.3 Splitting Blood Pressure Into Systolic and Diastolic Columns

In [29]:
print("Data type:", df['Blood_Pressure'].dtype)
print("Missing  :", df['Blood_Pressure'].isnull().sum())
print()
print(df[['Patient_ID', 'Diagnosis', 'Blood_Pressure']].to_string(index=False))

Data type: object
Missing  : 1

 Patient_ID    Diagnosis Blood_Pressure
          1     Diabetes         130/85
          2 Hypertension            NaN
          3          Flu         120/80
          4     Diabetes         135/90
          5 Hypertension         140/95
          6       Asthma         125/85
          7          Flu         118/75
          8 Hypertension        145/100
          9     Diabetes         130/90

In [30]:
bp_parts = df['Blood_Pressure'].str.strip().str.split('/', expand=True)

systolic  = pd.to_numeric(bp_parts[0], errors='coerce').astype('Int64')
diastolic = pd.to_numeric(bp_parts[1], errors='coerce').astype('Int64')

bp_position = df.columns.get_loc('Blood_Pressure')

df.insert(bp_position + 1, 'Systolic_BP', systolic)
df.insert(bp_position + 2, 'Diastolic_BP', diastolic)

print("Two numeric columns created")

Two numeric columns created

In [31]:
df[['Patient_ID', 'Blood_Pressure', 'Systolic_BP', 'Diastolic_BP']]

   Patient_ID Blood_Pressure  Systolic_BP  Diastolic_BP
0           1         130/85          130            85
1           2            NaN         <NA>          <NA>
2           3         120/80          120            80
3           4         135/90          135            90
4           5         140/95          140            95
5           6         125/85          125            85
6           7         118/75          118            75
7           8        145/100          145           100
8           9         130/90          130            90

In [32]:
df = df.drop(columns=['Blood_Pressure'])

print("Remaining columns:", list(df.columns))

Remaining columns: ['Patient_ID', 'Admission_Date', 'Name', 'Age', 'Gender', 'Diagnosis', 'Systolic_BP', 'Diastolic_BP', 'Heart_Rate', 'Medication', 'Doctor_Assigned', 'Contact_Number', 'Email']

### 2.4 Correcting Invalid Email Addresses

In [33]:
def fix_email(value):
    """
    Normalizes an address and repairs a domain with no suffix.

    The domain is only modified when it contains no dot at all,
    so a valid address is never touched.
    """
    email = str(value).strip().lower()

    if '@' not in email:
        return email

    local, _, domain = email.partition('@')

    if '.' not in domain:
        domain = domain + '.com'

    return local + '@' + domain

In [34]:
email_pattern = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'

email_before = df['Email'].copy()
df['Email'] = df['Email'].apply(fix_email)

pd.DataFrame({
    'Patient_ID': df['Patient_ID'],
    'Before': email_before,
    'Valid_Before': email_before.astype(str).str.match(email_pattern),
    'After': df['Email'],
    'Valid_After': df['Email'].str.match(email_pattern)
})

   Patient_ID            Before  Valid_Before                 After  Valid_After
0           1    john@email.com          True        john@email.com         True
1           2        jane@email         False        jane@email.com         True
2           3  mike.j@email.com          True      mike.j@email.com         True
3           4   sarah@email.com          True       sarah@email.com         True
4           5   chris@email.com          True       chris@email.com         True
5           6  emily.rose@email         False  emily.rose@email.com         True
6           7   kevin@email.com          True       kevin@email.com         True
7           8  olivia@email.com          True      olivia@email.com         True
8           9  daniel@email.com          True      daniel@email.com         True

In [35]:
print("Records modified:", (email_before != df['Email']).sum())
print("All addresses valid:", df['Email'].str.match(email_pattern).all())
print("Duplicate addresses:", df['Email'].duplicated().sum())

Records modified: 2
All addresses valid: True
Duplicate addresses: 0

### 2.5 Handling the Missing Contact Number

In [36]:
def fix_contact(value):
    """
    A phone number is an identifier, not a measurement,
    so the missing entry is labeled rather than estimated.
    """
    if pd.isna(value):
        return 'Not Provided'

    return str(int(value))

In [37]:
df['Contact_Number'] = df['Contact_Number'].apply(fix_contact)

pd.DataFrame({
    'Patient_ID': df['Patient_ID'],
    'Before': df_raw['Contact_Number'],
    'After': df['Contact_Number']
})

   Patient_ID        Before         After
0           1  9.876543e+09    9876543210
1           2  8.765432e+09    8765432109
2           3  7.654321e+09    7654321098
3           4  6.543211e+09    6543210987
4           5           NaN  Not Provided
5           6  5.432110e+09    5432109876
6           7  4.321099e+09    4321098765
7           8  3.210988e+09    3210987654
8           9  2.109877e+09    2109876543

### 2.6 Imputing the Missing Blood Pressure Reading

In [39]:
import numpy as np

group_systolic  = df.groupby('Diagnosis')['Systolic_BP'].transform('mean').astype('float')
group_diastolic = df.groupby('Diagnosis')['Diastolic_BP'].transform('mean').astype('float')

systolic_filled  = df['Systolic_BP'].astype('float').fillna(group_systolic)
diastolic_filled = df['Diastolic_BP'].astype('float').fillna(group_diastolic)

# Adding 0.5 before flooring forces a trailing .5 upward.
# Python rounds it to the nearest even number instead, so round(142.5) returns 142.
df['Systolic_BP']  = np.floor(systolic_filled + 0.5).astype('Int64')
df['Diastolic_BP'] = np.floor(diastolic_filled + 0.5).astype('Int64')

print("Blood pressure imputed using the diagnosis group mean")

Blood pressure imputed using the diagnosis group mean

In [40]:
print("Missing contact numbers:", (df['Contact_Number'] == 'Not Provided').sum())
print("Missing systolic  :", df['Systolic_BP'].isnull().sum())
print("Missing diastolic :", df['Diastolic_BP'].isnull().sum())
print()

df[['Patient_ID', 'Name', 'Diagnosis', 'Systolic_BP', 'Diastolic_BP', 'Contact_Number']]

Missing contact numbers: 1
Missing systolic  : 0
Missing diastolic : 0

   Patient_ID        Name     Diagnosis  Systolic_BP  Diastolic_BP Contact_Number
0           1  John Smith      Diabetes          130            85     9876543210
1           2    Jane Doe  Hypertension          143            98     8765432109
2           3  Mike Jones           Flu          120            80     7654321098
3           4   Sarah Lee      Diabetes          135            90     6543210987
4           5  Chris Paul  Hypertension          140            95   Not Provided
5           6  Emily Rose        Asthma          125            85     5432109876
6           7  Kevin Hart           Flu          118            75     4321098765
7           8  Olivia Kim  Hypertension          145           100     3210987654
8           9  Daniel Lee      Diabetes          130            90     2109876543

## Task 3 — Data Transformation

### 3.1 Recalculating the Missing Heart Rate by Diagnosis Group

In [41]:
print("Data type:", df['Heart_Rate'].dtype)
print("Missing  :", df['Heart_Rate'].isnull().sum())
print()
print("Overall mean heart rate:", round(df['Heart_Rate'].mean(), 2))
print()

df.groupby('Diagnosis')['Heart_Rate'].agg(['count', 'mean']).round(2)

Data type: float64
Missing  : 1

Overall mean heart rate: 78.88

              count   mean
Diagnosis
Asthma            1  78.00
Diabetes          3  76.67
Flu               1  70.00
Hypertension      3  84.33

In [42]:
group_heart_rate = df.groupby('Diagnosis')['Heart_Rate'].transform('mean')

heart_rate_filled = df['Heart_Rate'].fillna(group_heart_rate)

df['Heart_Rate'] = np.floor(heart_rate_filled + 0.5).astype('Int64')

print("Heart rate imputed using the diagnosis group mean")

Heart rate imputed using the diagnosis group mean

In [43]:
print("Missing heart rate values:", df['Heart_Rate'].isnull().sum())
print("Data type:", df['Heart_Rate'].dtype)
print()

pd.DataFrame({
    'Patient_ID': df['Patient_ID'],
    'Name': df['Name'],
    'Diagnosis': df['Diagnosis'],
    'HR_Before': df_raw['Heart_Rate'],
    'HR_After': df['Heart_Rate']
})

Missing heart rate values: 0
Data type: Int64

   Patient_ID        Name     Diagnosis  HR_Before  HR_After
0           1  John Smith      Diabetes       72.0        72
1           2    Jane Doe  Hypertension       80.0        80
2           3  Mike Jones           Flu        NaN        70
3           4   Sarah Lee      Diabetes       76.0        76
4           5  Chris Paul  Hypertension       85.0        85
5           6  Emily Rose        Asthma       78.0        78
6           7  Kevin Hart           Flu       70.0        70
7           8  Olivia Kim  Hypertension       88.0        88
8           9  Daniel Lee      Diabetes       82.0        82

### 3.2 Standardizing the Gender Column

In [44]:
print("Unique values:", df['Gender'].unique())
print("Trailing or leading spaces:", (df['Gender'] != df['Gender'].str.strip()).sum())
print()

df['Gender'].value_counts()

Unique values: ['Male' 'Female']
Trailing or leading spaces: 0

Gender
Male      5
Female    4
Name: count, dtype: int64

In [45]:
gender_map = {
    'm': 'Male',   'male': 'Male',     'man': 'Male',   'boy': 'Male',
    'f': 'Female', 'female': 'Female', 'woman': 'Female', 'girl': 'Female'
}

def standardize_gender(value):
    """
    Maps known spellings to a single canonical form.

    A value that is not in the map is returned cleaned rather
    than discarded, so an unexpected category stays visible
    instead of being silently absorbed into Unknown.
    """
    if pd.isna(value):
        return 'Unknown'

    key = str(value).strip().lower()

    if key in gender_map:
        return gender_map[key]

    return str(value).strip().title()

In [46]:
test_values = pd.Series(['male', ' FEMALE ', 'M', 'f', 'Male', 'woman', None, 'Non-binary'])

pd.DataFrame({
    'Input': test_values.astype(str),
    'Output': test_values.apply(standardize_gender)
})

        Input      Output
0        male        Male
1     FEMALE       Female
2           M        Male
3           f      Female
4        Male        Male
5       woman      Female
6        None     Unknown
7  Non-binary  Non-Binary

In [47]:
gender_before = df['Gender'].copy()
df['Gender'] = df['Gender'].apply(standardize_gender)

print("Records modified:", (gender_before != df['Gender']).sum())
print("Unique values after:", df['Gender'].unique())
print()

for column in ['Gender', 'Diagnosis', 'Medication', 'Doctor_Assigned']:
    print(f"{column:18} {sorted(df[column].unique())}")

Records modified: 0
Unique values after: ['Male' 'Female']

Gender             ['Female', 'Male']
Diagnosis          ['Asthma', 'Diabetes', 'Flu', 'Hypertension']
Medication         ['Albuterol', 'Ibuprofen', 'Lisinopril', 'Metformin']
Doctor_Assigned    ['Dr. Adams', 'Dr. Brown', 'Dr. White']

### 3.3 Sorting the Dataset by Admission Date

In [48]:
broken_dates = pd.to_datetime(df_raw['Admission_Date'], dayfirst=True, errors='coerce')

demonstration = pd.DataFrame({
    'Patient_ID': df_raw['Patient_ID'],
    'Name': df_raw['Name'],
    'Uncorrected_Date': broken_dates
})

demonstration.sort_values('Uncorrected_Date')

   Patient_ID        Name Uncorrected_Date
2           3  Mike Jones       2014-03-23
5           6  Emily Rose       2017-03-23
8           9  Daniel Lee       2020-03-23
0           1  John Smith       2023-03-12
4           5  Chris Paul       2023-03-16
6           7  Kevin Hart       2023-03-18
1           2    Jane Doe              NaT
3           4   Sarah Lee              NaT
7           8  Olivia Kim              NaT

In [49]:
df = df.sort_values('Admission_Date').reset_index(drop=True)

df[['Patient_ID', 'Admission_Date', 'Name', 'Diagnosis']]

   Patient_ID Admission_Date        Name     Diagnosis
0           1     2023-03-12  John Smith      Diabetes
1           2     2023-03-13    Jane Doe  Hypertension
2           3     2023-03-14  Mike Jones           Flu
3           4     2023-03-15   Sarah Lee      Diabetes
4           5     2023-03-16  Chris Paul  Hypertension
5           6     2023-03-17  Emily Rose        Asthma
6           7     2023-03-18  Kevin Hart           Flu
7           8     2023-03-19  Olivia Kim  Hypertension
8           9     2023-03-20  Daniel Lee      Diabetes

### 3.4 Renaming Columns to a Consistent snake_case Convention

In [52]:
import re
def to_snake_case(name):
    """
    Converts a column label to snake_case without a hardcoded map.

    Three passes:
      1. spaces and dashes become underscores
      2. an acronym followed by a word is split, so BPValue becomes BP_Value
      3. a lowercase or digit followed by a capital is split, so heartRate becomes heart_Rate
    """
    name = name.strip()
    name = re.sub(r'[\s\-]+', '_', name)
    name = re.sub(r'(?<=[A-Z])(?=[A-Z][a-z])', '_', name)
    name = re.sub(r'(?<=[a-z0-9])(?=[A-Z])', '_', name)
    name = re.sub(r'_+', '_', name)
    return name.lower()

test_labels = ['Patient_ID', 'Doctor Assigned', 'admissionDate', 'BPValue', '  Heart-Rate  ']

pd.DataFrame({
    'Input': test_labels,
    'Output': [to_snake_case(label) for label in test_labels]
})

             Input           Output
0       Patient_ID       patient_id
1  Doctor Assigned  doctor_assigned
2    admissionDate   admission_date
3          BPValue         bp_value
4     Heart-Rate         heart_rate

In [51]:
columns_before = list(df.columns)
df.columns = [to_snake_case(column) for column in df.columns]

pd.DataFrame({
    'Before': columns_before,
    'After': list(df.columns)
})

             Before            After
0        Patient_ID       patient_id
1    Admission_Date   admission_date
2              Name             name
3               Age              age
4            Gender           gender
5         Diagnosis        diagnosis
6       Systolic_BP      systolic_bp
7      Diastolic_BP     diastolic_bp
8        Heart_Rate       heart_rate
9        Medication       medication
10  Doctor_Assigned  doctor_assigned
11   Contact_Number   contact_number
12            Email            email

## Exporting the Cleaned Dataset

In [53]:
print("Rows   :", df.shape[0])
print("Columns:", df.shape[1])
print("Missing values remaining:", df.isnull().sum().sum())
print()

df.dtypes

Rows   : 9
Columns: 13
Missing values remaining: 0

patient_id                  int64
admission_date     datetime64[ns]
name                       object
age                         int64
gender                     object
diagnosis                  object
systolic_bp                 Int64
diastolic_bp                Int64
heart_rate                  Int64
medication                 object
doctor_assigned            object
contact_number             object
email                      object
dtype: object

In [54]:
df

   patient_id admission_date        name  age  gender     diagnosis  systolic_bp  diastolic_bp  heart_rate  medication doctor_assigned contact_number                 email
0           1     2023-03-12  John Smith   45    Male      Diabetes          130            85          72   Metformin       Dr. Adams     9876543210        john@email.com
1           2     2023-03-13    Jane Doe   32  Female  Hypertension          143            98          80  Lisinopril       Dr. Brown     8765432109        jane@email.com
2           3     2023-03-14  Mike Jones   29    Male           Flu          120            80          70   Ibuprofen       Dr. Adams     7654321098      mike.j@email.com
3           4     2023-03-15   Sarah Lee   43  Female      Diabetes          135            90          76   Metformin       Dr. White     6543210987       sarah@email.com
4           5     2023-03-16  Chris Paul   50    Male  Hypertension          140            95          85  Lisinopril       Dr. Brown   Not Provided       chris@email.com
5           6     2023-03-17  Emily Rose   41  Female        Asthma          125            85          78   Albuterol       Dr. Adams     5432109876  emily.rose@email.com
6           7     2023-03-18  Kevin Hart   38    Male           Flu          118            75          70   Ibuprofen       Dr. White     4321098765       kevin@email.com
7           8     2023-03-19  Olivia Kim   47  Female  Hypertension          145           100          88  Lisinopril       Dr. Brown     3210987654      olivia@email.com
8           9     2023-03-20  Daniel Lee   52    Male      Diabetes          130            90          82   Metformin       Dr. White     2109876543      daniel@email.com

In [55]:
export = df.copy()
export['admission_date'] = export['admission_date'].dt.strftime('%Y-%m-%d')

export.to_excel("Cleaned_Healthcare_Dataset.xlsx", index=False)
export.to_csv("Cleaned_Healthcare_Dataset.csv", index=False)

print("Files written to the notebook folder")

Files written to the notebook folder

In [56]:
verification = pd.read_excel("Cleaned_Healthcare_Dataset.xlsx")

print("Shape read back:", verification.shape)
print("Missing values :", verification.isnull().sum().sum())
print("Date stored as :", type(verification['admission_date'].iloc[0]).__name__)
print("First date     :", verification['admission_date'].iloc[0])
print()

verification.head()

Shape read back: (9, 13)
Missing values : 0
Date stored as : str
First date     : 2023-03-12

   patient_id admission_date        name  age  gender     diagnosis  systolic_bp  diastolic_bp  heart_rate  medication doctor_assigned contact_number             email
0           1     2023-03-12  John Smith   45    Male      Diabetes          130            85          72   Metformin       Dr. Adams     9876543210    john@email.com
1           2     2023-03-13    Jane Doe   32  Female  Hypertension          143            98          80  Lisinopril       Dr. Brown     8765432109    jane@email.com
2           3     2023-03-14  Mike Jones   29    Male           Flu          120            80          70   Ibuprofen       Dr. Adams     7654321098  mike.j@email.com
3           4     2023-03-15   Sarah Lee   43  Female      Diabetes          135            90          76   Metformin       Dr. White     6543210987   sarah@email.com
4           5     2023-03-16  Chris Paul   50    Male  Hypertension          140            95          85  Lisinopril       Dr. Brown   Not Provided   chris@email.com